### PR TITLE
feat: add GUI options regenerate project files

### PR DESCRIPTION
**Pull request by anggerdeni**
Add options to generate *.csproj files, taken mostly from vscode editor code

image

### CODE REVIEW

**Comment by anggerdeni** [comment]
Just wondering why is the `OnGUI` func left empty unlike that of vs code editor ? And whether it's a good idea to put it back in @Domeee

**Comment by Domeee** [comment]
Hi @anggerdeni and thanks for your PR! I like the OnGUI implementation :+1: 

The supported file name and the possible paths were hardcoded for neovim. This plugin aims to support neovim and its remote functionality. Thats why `var arguments = $"--server /tmp/nvimsocket --remote {filePath}";`. This opens a new instance of neovim if none is open or opens the file in the one started with `nvim --listen [servername]`.

**Comment by anggerdeni** [comment]
Got it @Domeee . I've reverted the changes to last commit, where I directly call terminal instead of utilizing nvim remote functionality.

**Comment by Domeee** [comment]
@anggerdeni  thank you for your work!

**Pull request merged**
